### PR TITLE
index.html fixed

### PR DESCRIPTION
**Pull request by szoszo23**
index.html get script tag

### CODE REVIEW

**Comment by koolstudent** [comment]
good one!

**Review by Emil9411 — APPROVED** [review]

**Review by PrkjLaci — APPROVED** [review]
fu de jó vagy

**Review by Tyna1992 — APPROVED** [review]
Nice work

**Comment by raberik98** [comment]
Wow I can't believe that you found it, well done!

**Comment by Emil9411** [comment]
GG EZ

**Pull request merged**
