### PR TITLE
I added some text to the text.txt

### PR DESCRIPTION
**Pull request by raberik98**

### CODE REVIEW

**Review by Tyna1992 — COMMENTED** [review]
Ide kéne írni?

**Comment by koolstudent** [comment]
Nicely done!

**Comment by szoszo23** [comment]
én is

**Review by acsidomi — APPROVED** [review]

**Review by Tyna1992 — APPROVED** [review]
Approved, well done! :)

**Comment by Emil9411** [comment]
It's perfect!

**Review by PrkjLaci — APPROVED** [review]

**Review by szoszo23 — COMMENTED** [review]
nekem nem tetszik :D

**Review by Emil9411 — APPROVED** [review]

**Comment by raberik98** [comment]
Ok I updated the project what do you think?

**Review by PrkjLaci — APPROVED** [review]

**Review by acsidomi — APPROVED** [review]

**Review by Emil9411 — APPROVED** [review]

**Review by szoszo23 — APPROVED** [review]

**Review by Tyna1992 — APPROVED** [review]

**Pull request merged**
